name: Create and register self-hosted runners

on:
  workflow_dispatch:
    inputs:
      useJobs:
        description: Use Container Apps jobs instead of Container Apps
        type: boolean
        default: true
        required: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: infra
    
jobs:
  provision-runners:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy self-hosted runners
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RG_NAME }}
          template: ./infra/02-runners/main.bicep
          parameters: >
            useJobs=${{ inputs.useJobs }}
            project=${{ vars.PROJECT }} 
            acrName=${{ vars.ACR_NAME }} 
            acaEnvName=${{ vars.ACA_ENV_NAME }} 
            acaMsiName=${{ vars.ACA_MSI_NAME }}
            imageTag=from-base
            gitHubAppId=${{ vars.GH_APP_ID }}
            gitHubAppInstallationId=${{ vars.GH_APP_INSTALLATION_ID }}
            gitHubAppKeySecretUri=${{ vars.GH_APP_PRIVATE_KEY_SECRET_URI }}
            gitHubOrganization=${{ github.repository_owner }} 
          deploymentName: deploy-aca-gh-runners
